mongodb:
  host: localhost
  port: 27017
  database: desafio

server: 
  port: 3009 

swApi: 
  host: https://swapi.co/api
  timeout: 3000

log:
  path: /var/log/desafio
  maxSize: 100000
  maxFiles: 10
  files:
    erro: desafio-erro.log
    info: desafio-info.log